# let Q8 be the quaternion group
# let J be the subgroup generated by j
# given a function phi in the table of marks of J
#   such that
#     phi[1] is the value at e
#     phi[2] is the value at C2
#     phi[3] is the value at J
# compute the marks of the norm nm_J^Q8(phi)

nmJQ := function(phi)
  local chi;
  chi := [];
  Add(chi, phi[1]*phi[1]);
  Add(chi, phi[2]*phi[2]);
  Add(chi, phi[2]);
  Add(chi, phi[2]*phi[3]);
  Add(chi, phi[2]);
  Add(chi, phi[3]);
  return chi;
end;;